extends: substitution
message: Unless you're referring to the general concept, consider using '%s' instead of '%s'.
level: suggestion
ignorecase: false
# swap maps tokens in form of bad: good
# for more information: https://vale.sh/docs/topics/styles/#substitution
swap:
  # Capitalize
  data grid: Data Grid
  date picker: Date Picker
  Data grid: Data Grid
  Date picker: Date Picker
  Time picker: Time Picker
  Date [t|T]ime picker: Date Time Picker
  Date [r|R]ange picker: Date Range Picker
  Time [r|R]ange picker: Time Range Picker
  Date [t|T]ime [r|R]ange picker: Date Time Range Picker
  time picker: Time Picker
  date time picker: Date Time Picker
  date range picker: Date Range Picker
  time range picker: Time Range Picker
  date time range picker: Date Time Range Picker
  # use Data Grid instead of grid
  the grid: the Data Grid
