name: Add reviewers to release PRs

on:
  pull_request_target:
    branches: ['master', 'next']
    types: ['labeled']

permissions: {}

jobs:
  add-reviewers:
    if: ${{ github.event.label.name == 'release' }}
    # Tests that label is added on the PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: get-members
        uses: garnertb/get-team-members@0482f68c88601800f85145570ea93bf8fcfcf46f
        with:
          org: mui
          team_slug: x
          role: maintainer
          token: ${{ secrets.GITHUB_TOKEN }}

      # assign reviewers
      - name: Add reviewer
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer <YOUR-TOKEN>" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
          -d '{"reviewers":[${{ steps.get-members.outputs.members }}]}' \
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
