name: Cherry pick v7 to v6

on:
  pull_request_target:
    branches:
      - v7.x
    types: ['closed']

permissions: {}

jobs:
  cherry_pick_v7_to_v6:
    runs-on: ubuntu-latest
    name: Cherry pick v7 into v6
    permissions:
      pull-requests: write
      contents: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'needs cherry-pick') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Cherry pick and create the new PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: carloscastrojumo/github-cherry-pick-action@503773289f4a459069c832dc628826685b75b4b3 # v1.0.10
        with:
          branch: v6.x
          body: 'Cherry-pick of #{old_pull_request_id}'
          cherry-pick-branch: ${{ format('cherry-pick-{0}', github.event.number) }}
          title: '{old_title} (@${{ github.event.pull_request.user.login }})'
          labels: |
            cherry-pick
