name: Add comment

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      BODY: |
        :warning: **This issue has been closed.**
        If you have a similar problem, please open a [new issue](https://github.com/mui/mui-x/issues/new/choose) and provide details about your specific problem.
        If you can provide additional information related to this topic that could help future readers, please feel free to leave a comment.
      APPENDIX: |

        **How did we do @${{ github.event.issue.user.login }}?**
        Your experience with our support team matters to us. If you have a moment, please share your thoughts through our [brief survey](https://tally.so/r/w4r5Mk?issue=${{ github.event.issue.number }}).

    if: github.event.issue.state_reason != 'inactivity'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions-cool/check-user-permission@a0668c9aec87f3875fc56170b6452a453e9dd819
        id: checkUser
        with:
          require: 'write'
      - name: Add comment for outside contributors
        if: steps.checkUser.outputs.check-result == 'false'
        run: gh issue comment "$NUMBER" --body "$BODY $APPENDIX"
      - name: Add comment for maintainers
        if: steps.checkUser.outputs.check-result == 'true'
        run: gh issue comment "$NUMBER" --body "$BODY"
