name: Update missing translations

on:
  push:
    branches:
      - master
      - next

jobs:
  # Tests dev-only scripts across all supported dev environments
  update-l10n:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: yarn install
        env:
          # Don't need playwright in this job
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: yarn l10n --report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote -v
          yarn l10n --report
