name: Order ID validation

on:
  workflow_run:
    workflows: [Issue cleanup]
    types:
      - completed

permissions: {}

jobs:
  validate-order-id:
    runs-on: ubuntu-latest
    name: Label issue based on order ID
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Label issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/orderIdValidation.js')
            await script({core, github, context})
        env:
          ORDER_API_TOKEN: ${{ secrets.SHOP_AUTH_TOKEN }}
