name: Order ID validation

on:
  workflow_run:
    workflows:
      - Cleanup issue comment
    types:
      - completed

permissions: {}

jobs:
  validate-order-id:
    runs-on: ubuntu-latest
    name: Label issue based on order ID
    permissions:
      actions: read
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Label issue
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const script = require('./scripts/orderIdValidation.js')
            await script({core, github, context})
        env:
          ORDER_API_TOKEN: ${{ secrets.SHOP_AUTH_TOKEN }}
